### ISSUE TITLE
Could not pass event ChunkLoadEvent to StackMobBridge

### ISSUE THREAD

**Issue by s1h4d0w** [Nathat23/StackMob-5#109]
Getting this error continually spammed to console when players move and load chunks (not generate new ones). I upgraded my server from 1.14.4 to 1.15.2 recently, already googled what the StackMobBridge plugin does, but I guess something goes wrong with converting.

Running paper 1.15.2.

```
[00:32:55 ERROR]: Could not pass event ChunkLoadEvent to StackMobBridge v2.0.1-SNAPSHOT
java.lang.IllegalArgumentException: Stack size can not be less than one!
at uk.antiperson.stackmob.entity.StackEntity.setSize(StackEntity.java:36) ~[?:?]
at uk.antiperson.stackmob.entity.StackEntity.setSize(StackEntity.java:27) ~[?:?]
at uk.antiperson.stackmobbridge.StackMobBridge.convertEntities(StackMobBridge.java:77) ~[?:?]
at uk.antiperson.stackmobbridge.ChunkLoad.onChunkLoad(ChunkLoad.java:16) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor681.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-376]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-376]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-376]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-376]
at net.minecraft.server.v1_15_R1.Chunk.loadCallback(Chunk.java:862) ~[patched_1.15.2.jar:git-Paper-376]
at net.minecraft.server.v1_15_R1.PlayerChunk.lambda$null$14(PlayerChunk.java:747) ~[patched_1.15.2.jar:git-Paper-376]
at net.minecraft.server.v1_15_R1.PlayerChunkMap$CallbackExecutor.run(PlayerChunkMap.java:145) ~[patched_1.15.2.jar:git-Paper-376]
at net.minecraft.server.v1_15_R1.PlayerChunk.a(PlayerChunk.java:757) ~[patched_1.15.2.jar:git-Paper-376]
at net.minecraft.server.v1_15_R1.ChunkMapDistance.a(ChunkMapDistance.java:117) ~[patched_1.15.2.jar:git-Paper-376]
at net.minecraft.server.v1_15_R1.ChunkProviderServer.tickDistanceManager(ChunkProviderServer.java:639) ~[patched_1.15.2.jar:git-Paper-376]
at net.minecraft.server.v1_15_R1.ChunkProviderServer.tick(ChunkProviderServer.java:745) ~[patched_1.15.2.jar:git-Paper-376]
at net.minecraft.server.v1_15_R1.WorldServer.doTick(WorldServer.java:439) ~[patched_1.15.2.jar:git-Paper-376]
```

**Comment by Nathat23** [comment]
does this occur all the time or just randomly?
did you use a database for mob data or just flat file (default) storage method?

**Comment by s1h4d0w** [comment]
This happens when moving around and loading chunks (I assume with mobs in them), and I use a flat file.

**Comment by Nathat23** [comment]
Coul you provide both files in the stackmobbridge folder, found in the plugins folder?
