### ISSUE TITLE
EntityDeathEvent error

### ISSUE THREAD

**Issue by LogGits** [Nathat23/StackMob-5#125]
```
ERROR 15:59:21
Could not pass event EntityDeathEvent to StackMob v5.2.3
Console 15:59:21
java.lang.NullPointerException: null
at uk.antiperson.stackmob.config.MainConfig.getDeathType(MainConfig.java:182) ~[?:?]
at uk.antiperson.stackmob.listeners.DeathListener.calculateDeath(DeathListener.java:66) ~[?:?]
at uk.antiperson.stackmob.listeners.DeathListener.onStackDeath(DeathListener.java:38) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor563.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.2.jar:git-Paper-184]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.2.jar:git-Paper-184]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.2.jar:git-Paper-184]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.2.jar:git-Paper-184]
at org.bukkit.craftbukkit.v1_16_R2.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:801) ~[patched_1.16.2.jar:git-Paper-184]
at net.minecraft.server.v1_16_R2.EntityLiving.d(EntityLiving.java:1491) ~[patched_1.16.2.jar:git-Paper-184]
at net.minecraft.server.v1_16_R2.EntityLiving.die(EntityLiving.java:1420) ~[patched_1.16.2.jar:git-Paper-184]
at net.minecraft.server.v1_16_R2.EntityLiving.damageEntity(EntityLiving.java:1262) ~[patched_1.16.2.jar:git-Paper-184]
at net.minecraft.server.v1_16_R2.EntitySquid.damageEntity(EntitySquid.java:138) ~[patched_1.16.2.jar:git-Paper-184]
at net.minecraft.server.v1_16_R2.EntityWaterAnimal.a(SourceFile:49) ~[patched_1.16.2.jar:git-Paper-184]
at net.minecraft.server.v1_16_R2.EntityWaterAnimal.entityBaseTick(SourceFile:60) ~[patched_1.16.2.jar:git-Paper-184]
at net.minecraft.server.v1_16_R2.Entity.tick(Entity.java:407) ~[patched_1.16.2.jar:git-Paper-184]
at net.minecraft.server.v1_16_R2.EntityLiving.tick(EntityLiving.java:2429) ~[patched_1.16.2.jar:git-Paper-184]
at net.minecraft.server.v1_16_R2.EntityInsentient.tick(EntityInsentient.java:306) ~[patched_1.16.2.jar:git-Paper-184]
at net.minecraft.server.v1_16_R2.WorldServer.entityJoinedWorld(WorldServer.java:834) ~[patched_1.16.2.jar:git-Paper-184]
at net.minecraft.server.v1_16_R2.World.a(World.java:893) ~[patched_1.16.2.jar:git-Paper-184]
at net.minecraft.server.v1_16_R2.WorldServer.doTick(WorldServer.java:526) ~[patched_1.16.2.jar:git-Paper-184]
at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1358) ~[patched_1.16.2.jar:git-Paper-184]
at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:375) ~[patched_1.16.2.jar:git-Paper-184]
at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1211) ~[patched_1.16.2.jar:git-Paper-184]
at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999) ~[patched_1.16.2.jar:git-Paper-184]
at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.2.jar:git-Paper-184]
at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by Nathat23** [comment]
This is because you downgraded version. I'll merge your changes and release an update.
