### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by LogGits** [Nathat23/StackMob-5#136]
Don't have time to look into fixing it but i got this error and posting so i dont forget:
```
ERROR 22:29:31
Could not pass event ChunkUnloadEvent to StackMob v5.3.4
Console 22:29:31
java.lang.UnsupportedOperationException: Attempted to unregister entity that isn't stacked!
at uk.antiperson.stackmob.entity.EntityManager.unregisterStackedEntity(EntityManager.java:94) ~[?:?]
at uk.antiperson.stackmob.entity.EntityManager.unregisterStackedEntities(EntityManager.java:77) ~[?:?]
at uk.antiperson.stackmob.listeners.ChunkListener.onChunkUnload(ChunkListener.java:23) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor567.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.3.jar:git-Paper-197]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.3.jar:git-Paper-197]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.3.jar:git-Paper-197]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.3.jar:git-Paper-197]
at net.minecraft.server.v1_16_R2.Chunk.unloadCallback(Chunk.java:846) ~[patched_1.16.3.jar:git-Paper-197]
at net.minecraft.server.v1_16_R2.PlayerChunk.lambda$null$7(PlayerChunk.java:578) ~[patched_1.16.3.jar:git-Paper-197]
at net.minecraft.server.v1_16_R2.PlayerChunkMap$CallbackExecutor.run(PlayerChunkMap.java:149) ~[patched_1.16.3.jar:git-Paper-197]
at net.minecraft.server.v1_16_R2.PlayerChunk.a(PlayerChunk.java:588) ~[patched_1.16.3.jar:git-Paper-197]
at net.minecraft.server.v1_16_R2.ChunkMapDistance.a(ChunkMapDistance.java:117) ~[patched_1.16.3.jar:git-Paper-197]
at net.minecraft.server.v1_16_R2.ChunkProviderServer.tickDistanceManager(ChunkProviderServer.java:641) ~[patched_1.16.3.jar:git-Paper-197]
at net.minecraft.server.v1_16_R2.ChunkProviderServer.tick(ChunkProviderServer.java:739) ~[patched_1.16.3.jar:git-Paper-197]
at net.minecraft.server.v1_16_R2.WorldServer.doTick(WorldServer.java:456) ~[patched_1.16.3.jar:git-Paper-197]
at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1358) ~[patched_1.16.3.jar:git-Paper-197]
at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:371) ~[patched_1.16.3.jar:git-Paper-197]
at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1211) ~[patched_1.16.3.jar:git-Paper-197]
at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999) ~[patched_1.16.3.jar:git-Paper-197]
at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-197]
at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by Nathat23** [comment]
Fixed in 2e670da8f6c8256d52efcb14d7650b3a77793195
