### ISSUE TITLE
Console Output's error log. (EntityDeathEvent)

### ISSUE THREAD

**Issue by Blizz2210** [Nathat23/StackMob-5#137]
`[23:47:02] [Server thread/ERROR]: Could not pass event EntityDeathEvent to StackMob v5.3.4
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[Spigot.jar:git-Spigot-a99063f-c9d7c16]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[Spigot.jar:git-Spigot-a99063f-c9d7c16]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[Spigot.jar:git-Spigot-a99063f-c9d7c16]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[Spigot.jar:git-Spigot-a99063f-c9d7c16]
	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:729) ~[Spigot.jar:git-Spigot-a99063f-c9d7c16]
	at net.minecraft.server.v1_15_R1.EntityLiving.d(EntityLiving.java:1328) ~[Spigot.jar:git-Spigot-a99063f-c9d7c16]
	at net.minecraft.server.v1_15_R1.EntityLiving.die(EntityLiving.java:1277) ~[Spigot.jar:git-Spigot-a99063f-c9d7c16]
	at net.minecraft.server.v1_15_R1.EntityLiving.damageEntity(EntityLiving.java:1124) ~[Spigot.jar:git-Spigot-a99063f-c9d7c16]
	at net.minecraft.server.v1_15_R1.EntityMonster.damageEntity(SourceFile:69) ~[Spigot.jar:git-Spigot-a99063f-c9d7c16]
	at net.minecraft.server.v1_15_R1.EntityHuman.attack(EntityHuman.java:1085) ~[Spigot.jar:git-Spigot-a99063f-c9d7c16]
	at net.minecraft.server.v1_15_R1.EntityPlayer.attack(EntityPlayer.java:1547) ~[Spigot.jar:git-Spigot-a99063f-c9d7c16]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1879) ~[Spigot.jar:git-Spigot-a99063f-c9d7c16]
	at net.minecraft.server.v1_15_R1.PacketPlayInUseEntity.a(SourceFile:68) ~[Spigot.jar:git-Spigot-a99063f-c9d7c16]
	at net.minecraft.server.v1_15_R1.PacketPlayInUseEntity.a(SourceFile:13) ~[Spigot.jar:git-Spigot-a99063f-c9d7c16]
	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[Spigot.jar:git-Spigot-a99063f-c9d7c16]
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) [Spigot.jar:git-Spigot-a99063f-c9d7c16]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [Spigot.jar:git-Spigot-a99063f-c9d7c16]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [Spigot.jar:git-Spigot-a99063f-c9d7c16]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [Spigot.jar:git-Spigot-a99063f-c9d7c16]
	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:918) [Spigot.jar:git-Spigot-a99063f-c9d7c16]
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:911) [Spigot.jar:git-Spigot-a99063f-c9d7c16]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [Spigot.jar:git-Spigot-a99063f-c9d7c16]
	at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:895) [Spigot.jar:git-Spigot-a99063f-c9d7c16]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:828) [Spigot.jar:git-Spigot-a99063f-c9d7c16]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]
Caused by: java.lang.IllegalArgumentException: Health must be between 0 and 12.0(26.5)
	at org.bukkit.craftbukkit.v1_15_R1.entity.CraftLivingEntity.setHealth(CraftLivingEntity.java:109) ~[Spigot.jar:git-Spigot-a99063f-c9d7c16]
	at uk.antiperson.stackmob.entity.death.KillStepDamage.onSpawn(KillStepDamage.java:47) ~[?:?]
	at uk.antiperson.stackmob.listeners.DeathListener.onStackDeath(DeathListener.java:46) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor218.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_261]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_261]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[Spigot.jar:git-Spigot-a99063f-c9d7c16]
	... 24 more`

I changed nothing in the config, yet after installing this error is being constantly popping up in the console.

**Comment by Nathat23** [comment]
Fixed in e292039d00c5ffb85483a4afcd6383ada964687c
