### ISSUE TITLE
ERROR Could not pass event EntityDeathEvent to StackMob v5.3.5

### ISSUE THREAD

**Issue by rrvk** [Nathat23/StackMob-5#146]
I am getting these error's in my console logging
```
java.lang.IllegalArgumentException: Parameters not allowed in this parameter set: [<parameter minecraft:origin>]
        at net.minecraft.server.v1_16_R2.LootTableInfo$Builder.build(SourceFile:203) ~[patched_1.16.3.jar:git-Paper-214]
        at org.bukkit.craftbukkit.v1_16_R2.CraftLootTable.convertContext(CraftLootTable.java:115) ~[patched_1.16.3.jar:git-Paper-214]
        at org.bukkit.craftbukkit.v1_16_R2.CraftLootTable.populateLoot(CraftLootTable.java:44) ~[patched_1.16.3.jar:git-Paper-214]
        at uk.antiperson.stackmob.entity.Drops.calculateLoot(Drops.java:75) ~[?:?]
        at uk.antiperson.stackmob.entity.Drops.calculateDrops(Drops.java:40) ~[?:?]
        at uk.antiperson.stackmob.listeners.DeathListener.onStackDeath(DeathListener.java:54) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor240.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.3.jar:git-Paper-214]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.3.jar:git-Paper-214]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.3.jar:git-Paper-214]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.3.jar:git-Paper-214]
        at org.bukkit.craftbukkit.v1_16_R2.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:801) ~[patched_1.16.3.jar:git-Paper-214]
        at net.minecraft.server.v1_16_R2.EntityLiving.d(EntityLiving.java:1491) ~[patched_1.16.3.jar:git-Paper-214]
        at net.minecraft.server.v1_16_R2.EntityLiving.die(EntityLiving.java:1420) ~[patched_1.16.3.jar:git-Paper-214]
        at net.minecraft.server.v1_16_R2.EntityLiving.damageEntity(EntityLiving.java:1262) ~[patched_1.16.3.jar:git-Paper-214]
        at net.minecraft.server.v1_16_R2.EntityIronGolem.attackEntity(EntityIronGolem.java:149) ~[patched_1.16.3.jar:git-Paper-214]
        at net.minecraft.server.v1_16_R2.PathfinderGoalMeleeAttack.a(SourceFile:142) ~[patched_1.16.3.jar:git-Paper-214]
        at net.minecraft.server.v1_16_R2.PathfinderGoalMeleeAttack.e(SourceFile:134) ~[patched_1.16.3.jar:git-Paper-214]
        at net.minecraft.server.v1_16_R2.PathfinderGoalWrapped.e(PathfinderGoalWrapped.java:54) ~[patched_1.16.3.jar:git-Paper-214]
        at net.minecraft.server.v1_16_R2.PathfinderGoalSelector.doTick(PathfinderGoalSelector.java:153) ~[patched_1.16.3.jar:git-Paper-214]
        at net.minecraft.server.v1_16_R2.EntityInsentient.doTick(EntityInsentient.java:757) ~[patched_1.16.3.jar:git-Paper-214]
        at net.minecraft.server.v1_16_R2.EntityLiving.movementTick(EntityLiving.java:2753) ~[patched_1.16.3.jar:git-Paper-214]
        at net.minecraft.server.v1_16_R2.EntityInsentient.movementTick(EntityInsentient.java:543) ~[patched_1.16.3.jar:git-Paper-214]
        at net.minecraft.server.v1_16_R2.EntityIronGolem.movementTick(EntityIronGolem.java:69) ~[patched_1.16.3.jar:git-Paper-214]
        at net.minecraft.server.v1_16_R2.EntityLiving.tick(EntityLiving.java:2478) ~[patched_1.16.3.jar:git-Paper-214]
        at net.minecraft.server.v1_16_R2.EntityInsentient.tick(EntityInsentient.java:306) ~[patched_1.16.3.jar:git-Paper-214]
        at net.minecraft.server.v1_16_R2.WorldServer.entityJoinedWorld(WorldServer.java:841) ~[patched_1.16.3.jar:git-Paper-214]
        at net.minecraft.server.v1_16_R2.World.a(World.java:884) ~[patched_1.16.3.jar:git-Paper-214]
        at net.minecraft.server.v1_16_R2.WorldServer.doTick(WorldServer.java:526) ~[patched_1.16.3.jar:git-Paper-214]
        at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1358) ~[patched_1.16.3.jar:git-Paper-214]
        at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:371) ~[patched_1.16.3.jar:git-Paper-214]
        at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1211) ~[patched_1.16.3.jar:git-Paper-214]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999) ~[patched_1.16.3.jar:git-Paper-214]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-214]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
```

I am using `Paper-214` (1.16.3 version)

And my previous version was `Paper-207` (1.16.3) And then i had the issue not

**Comment by Nathat23** [comment]
Do you know how to reproduce?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by rrvk** [comment]
Yeah sure, i have tested it on the default configuration and these are the steps to reproduce it:

1. Have an iron golem (stacked or not stacked it does not matter)
2. Then spawn some slime around the irom golem so the slimes are going to stack (it needs to be slime large enoug to damage the iron golem)
3. when that happens the error occurs

**Comment by Nathat23** [comment]
It's a bug in spigot. I've reported it at https://hub.spigotmc.org/jira/projects/SPIGOT/issues/SPIGOT-6175?filter=allissues

**Comment by Nathat23** [comment]
This bug has been fixed in Spigot.

**Comment by rrvk** [comment]
Yeah i saw that is also was ported to paper and i tryed it and it is been fixed, thanks!
