### ISSUE TITLE
ERROR Could not pass event ChunkUnloadEvent to StackMob v5.3.5

### ISSUE THREAD

**Issue by arturkosidlo** [Nathat23/StackMob-5#148]
[21:24:27] [Server thread/ERROR]: Could not pass event ChunkUnloadEvent to StackMob v5.3.5
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[mc.jar:git-Spigot-2740d5a-890130b]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[mc.jar:git-Spigot-2740d5a-890130b]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[mc.jar:git-Spigot-2740d5a-890130b]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[mc.jar:git-Spigot-2740d5a-890130b]
at net.minecraft.server.v1_16_R2.Chunk.unloadCallback(Chunk.java:546) ~[mc.jar:git-Spigot-2740d5a-890130b]
at net.minecraft.server.v1_16_R2.PlayerChunk.lambda$6(PlayerChunk.java:295) ~[mc.jar:git-Spigot-2740d5a-890130b]
at net.minecraft.server.v1_16_R2.PlayerChunkMap$CallbackExecutor.run(PlayerChunkMap.java:98) ~[mc.jar:git-Spigot-2740d5a-890130b]
at net.minecraft.server.v1_16_R2.PlayerChunk.a(PlayerChunk.java:305) ~[mc.jar:git-Spigot-2740d5a-890130b]
at net.minecraft.server.v1_16_R2.ChunkMapDistance.a(ChunkMapDistance.java:107) ~[mc.jar:git-Spigot-2740d5a-890130b]
at net.minecraft.server.v1_16_R2.ChunkProviderServer.tickDistanceManager(ChunkProviderServer.java:265) ~[mc.jar:git-Spigot-2740d5a-890130b]
at net.minecraft.server.v1_16_R2.ChunkProviderServer.tick(ChunkProviderServer.java:343) ~[mc.jar:git-Spigot-2740d5a-890130b]
at net.minecraft.server.v1_16_R2.WorldServer.doTick(WorldServer.java:329) ~[mc.jar:git-Spigot-2740d5a-890130b]
at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1104) ~[mc.jar:git-Spigot-2740d5a-890130b]
at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:349) ~[mc.jar:git-Spigot-2740d5a-890130b]
at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1007) ~[mc.jar:git-Spigot-2740d5a-890130b]
at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:846) ~[mc.jar:git-Spigot-2740d5a-890130b]
at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[mc.jar:git-Spigot-2740d5a-890130b]
at java.lang.Thread.run(Thread.java:830) [?:?]
Caused by: java.lang.UnsupportedOperationException: Attempted to unregister entity that isn't stacked!
at uk.antiperson.stackmob.entity.EntityManager.unregisterStackedEntity(EntityManager.java:94) ~[?:?]
at uk.antiperson.stackmob.entity.EntityManager.unregisterStackedEntities(EntityManager.java:77) ~[?:?]
at uk.antiperson.stackmob.listeners.ChunkListener.onChunkUnload(ChunkListener.java:23) ~[?:?]
at jdk.internal.reflect.GeneratedMethodAccessor947.invoke(Unknown Source) ~[?:?]
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[mc.jar:git-Spigot-2740d5a-890130b]
[21:25:02] [Server thread/WARN]: Unable to create attribute: null
[21:25:23] [Server thread/WARN]: Unable to create attribute: null
[21:25:47] [Server thread/INFO]: Arczix12 issued server command: /mc
[21:27:42] [Craft Scheduler Thread - 2108/INFO]: Zapraszamy na serwer Discord! https://discord.gg/ajFR44K
[21:28:13] [Server thread/INFO]: Arczix12 issued server command: /home nether
[21:28:16] [Server thread/ERROR]: Could not pass event ChunkUnloadEvent to StackMob v5.3.5
at net.minecraft.server.v1_16_R2.ChunkProviderServer.access$4(ChunkProviderServer.java:264) ~[mc.jar:git-Spigot-2740d5a-890130b]
at net.minecraft.server.v1_16_R2.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:560) ~[mc.jar:git-Spigot-2740d5a-890130b]
at net.minecraft.server.v1_16_R2.ChunkProviderServer.runTasks(ChunkProviderServer.java:261) ~[mc.jar:git-Spigot-2740d5a-890130b]
at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:950) ~[mc.jar:git-Spigot-2740d5a-890130b]
at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:934) ~[mc.jar:git-Spigot-2740d5a-890130b]
at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeAll(SourceFile:103) ~[mc.jar:git-Spigot-2740d5a-890130b]
at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:917) ~[mc.jar:git-Spigot-2740d5a-890130b]
at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:850) ~[mc.jar:git-Spigot-2740d5a-890130b]

**Comment by Aurelien30000** [comment]
Stackmob works but with some troubles on spigot, as you saw with these errors.
I just recommend you to migrate to Paper, only lots of benefits for all your server (stability performance, better support of plugins, etc)

**Comment by Aquerr** [comment]
I am getting the same error using StackMob v5.3.7.
