### ISSUE TITLE
Errorz

### ISSUE THREAD

**Issue by LogGits** [Nathat23/StackMob-5#158]
Got da error flying around world with elytra:
```
ERROR 00:50:38
Could not pass event ChunkLoadEvent to StackMobBridge v2.0.1-SNAPSHOT
Console 00:50:38
java.lang.NullPointerException: null
at uk.antiperson.stackmobbridge.StackMobBridge.convertEntities(StackMobBridge.java:77) ~[?:?]
at uk.antiperson.stackmobbridge.ChunkLoad.onChunkLoad(ChunkLoad.java:16) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor580.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.4.jar:git-Paper-279]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.4.jar:git-Paper-279]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.4.jar:git-Paper-279]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.4.jar:git-Paper-279]
at net.minecraft.server.v1_16_R3.Chunk.loadCallback(Chunk.java:818) ~[patched_1.16.4.jar:git-Paper-279]
at net.minecraft.server.v1_16_R3.PlayerChunk.lambda$null$15(PlayerChunk.java:745) ~[patched_1.16.4.jar:git-Paper-279]
at net.minecraft.server.v1_16_R3.PlayerChunkMap$CallbackExecutor.run(PlayerChunkMap.java:149) ~[patched_1.16.4.jar:git-Paper-279]
at net.minecraft.server.v1_16_R3.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:1054) ~[patched_1.16.4.jar:git-Paper-279]
at net.minecraft.server.v1_16_R3.ChunkProviderServer$a.midTickLoadChunks(ChunkProviderServer.java:1031) ~[patched_1.16.4.jar:git-Paper-279]
at net.minecraft.server.v1_16_R3.MinecraftServer.midTickLoadChunks(MinecraftServer.java:1105) ~[patched_1.16.4.jar:git-Paper-279]
at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:470) ~[patched_1.16.4.jar:git-Paper-279]
at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1359) ~[patched_1.16.4.jar:git-Paper-279]
at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.4.jar:git-Paper-279]
at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1212) ~[patched_1.16.4.jar:git-Paper-279]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1000) ~[patched_1.16.4.jar:git-Paper-279]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.4.jar:git-Paper-279]
at java.lang.Thread.run(Thread.java:834) [?:?]
ERROR 00:51:03
Could not pass event ChunkLoadEvent to StackMobBridge v2.0.1-SNAPSHOT
Console 00:51:03
java.lang.NullPointerException: null
at uk.antiperson.stackmobbridge.StackMobBridge.convertEntities(StackMobBridge.java:77) ~[?:?]
at uk.antiperson.stackmobbridge.ChunkLoad.onChunkLoad(ChunkLoad.java:16) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor580.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.4.jar:git-Paper-279]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.4.jar:git-Paper-279]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.4.jar:git-Paper-279]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.4.jar:git-Paper-279]
at net.minecraft.server.v1_16_R3.Chunk.loadCallback(Chunk.java:818) ~[patched_1.16.4.jar:git-Paper-279]
at net.minecraft.server.v1_16_R3.PlayerChunk.lambda$null$15(PlayerChunk.java:745) ~[patched_1.16.4.jar:git-Paper-279]
at net.minecraft.server.v1_16_R3.PlayerChunkMap$CallbackExecutor.run(PlayerChunkMap.java:149) ~[patched_1.16.4.jar:git-Paper-279]
at net.minecraft.server.v1_16_R3.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:1054) ~[patched_1.16.4.jar:git-Paper-279]
at net.minecraft.server.v1_16_R3.ChunkProviderServer.runTasks(ChunkProviderServer.java:636) ~[patched_1.16.4.jar:git-Paper-279]
at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1145) ~[patched_1.16.4.jar:git-Paper-279]
at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1129) ~[patched_1.16.4.jar:git-Paper-279]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.4.jar:git-Paper-279]
at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1090) ~[patched_1.16.4.jar:git-Paper-279]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1004) ~[patched_1.16.4.jar:git-Paper-279]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.4.jar:git-Paper-279]
at java.lang.Thread.run(Thread.java:834) [?:?]
```
v 5.3.6
paper 1.16.4 build 277

**Comment by LogGits** [comment]
Paper 1.16.5 build 634
SM 5.5.4
SMB 2.0.1

Noticed this error again:
```
ERROR16:48:46
Could not pass event ChunkLoadEvent to StackMobBridge v2.0.1-SNAPSHOT
Console16:48:46
java.lang.NullPointerException: null
at uk.antiperson.stackmobbridge.StackMobBridge.convertEntities(StackMobBridge.java:77) ~[?:?]
at uk.antiperson.stackmobbridge.ChunkLoad.onChunkLoad(ChunkLoad.java:16) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor516.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-644]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-644]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-644]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-644]
at net.minecraft.server.v1_16_R3.Chunk.loadCallback(Chunk.java:875) ~[patched_1.16.5.jar:git-Paper-644]
at net.minecraft.server.v1_16_R3.PlayerChunk.lambda$null$15(PlayerChunk.java:775) ~[patched_1.16.5.jar:git-Paper-644]
at net.minecraft.server.v1_16_R3.PlayerChunkMap$CallbackExecutor.run(PlayerChunkMap.java:204) ~[patched_1.16.5.jar:git-Paper-644]
at net.minecraft.server.v1_16_R3.PlayerChunk.a(PlayerChunk.java:785) ~[patched_1.16.5.jar:git-Paper-644]
at net.minecraft.server.v1_16_R3.ChunkMapDistance.a(ChunkMapDistance.java:126) ~[patched_1.16.5.jar:git-Paper-644]
at net.minecraft.server.v1_16_R3.ChunkProviderServer.tickDistanceManager(ChunkProviderServer.java:665) ~[patched_1.16.5.jar:git-Paper-644]
at net.minecraft.server.v1_16_R3.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:1070) ~[patched_1.16.5.jar:git-Paper-644]
at net.minecraft.server.v1_16_R3.ChunkProviderServer.runTasks(ChunkProviderServer.java:660) ~[patched_1.16.5.jar:git-Paper-644]
at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1271) ~[patched_1.16.5.jar:git-Paper-644]
at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1255) ~[patched_1.16.5.jar:git-Paper-644]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-644]
at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1216) ~[patched_1.16.5.jar:git-Paper-644]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1130) ~[patched_1.16.5.jar:git-Paper-644]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-644]
at java.lang.Thread.run(Thread.java:834) [?:?]
```
