### ISSUE TITLE
Could not pass event ChunkUnloadEvent to StackMob v5.4.1

### ISSUE THREAD

**Issue by ScorpioMc** [Nathat23/StackMob-5#180]
Hey ! I'm using your plugin but I found a bug when it's active :

`[Server thread/ERROR]: Could not pass event ChunkUnloadEvent to StackMob v5.4.1
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[spigot-1.16.4.jar:git-Spigot-aa47792-6fd677c]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.16.4.jar:git-Spigot-aa47792-6fd677c]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-1.16.4.jar:git-Spigot-aa47792-6fd677c]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.16.4.jar:git-Spigot-aa47792-6fd677c]
	at net.minecraft.server.v1_16_R3.Chunk.unloadCallback(Chunk.java:549) ~[spigot-1.16.4.jar:git-Spigot-aa47792-6fd677c]
	at net.minecraft.server.v1_16_R3.PlayerChunk.lambda$6(PlayerChunk.java:295) ~[spigot-1.16.4.jar:git-Spigot-aa47792-6fd677c]
	at net.minecraft.server.v1_16_R3.PlayerChunkMap$CallbackExecutor.run(PlayerChunkMap.java:98) ~[spigot-1.16.4.jar:git-Spigot-aa47792-6fd677c]
	at net.minecraft.server.v1_16_R3.PlayerChunk.a(PlayerChunk.java:305) ~[spigot-1.16.4.jar:git-Spigot-aa47792-6fd677c]
	at net.minecraft.server.v1_16_R3.ChunkMapDistance.a(ChunkMapDistance.java:107) ~[spigot-1.16.4.jar:git-Spigot-aa47792-6fd677c]
	at net.minecraft.server.v1_16_R3.ChunkProviderServer.tickDistanceManager(ChunkProviderServer.java:265) ~[spigot-1.16.4.jar:git-Spigot-aa47792-6fd677c]
	at net.minecraft.server.v1_16_R3.ChunkProviderServer.access$4(ChunkProviderServer.java:264) ~[spigot-1.16.4.jar:git-Spigot-aa47792-6fd677c]
	at net.minecraft.server.v1_16_R3.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:560) ~[spigot-1.16.4.jar:git-Spigot-aa47792-6fd677c]
	at net.minecraft.server.v1_16_R3.ChunkProviderServer.runTasks(ChunkProviderServer.java:261) ~[spigot-1.16.4.jar:git-Spigot-aa47792-6fd677c]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:950) ~[spigot-1.16.4.jar:git-Spigot-aa47792-6fd677c]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:934) ~[spigot-1.16.4.jar:git-Spigot-aa47792-6fd677c]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeAll(SourceFile:103) ~[spigot-1.16.4.jar:git-Spigot-aa47792-6fd677c]
	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:917) ~[spigot-1.16.4.jar:git-Spigot-aa47792-6fd677c]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:850) ~[spigot-1.16.4.jar:git-Spigot-aa47792-6fd677c]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.4.jar:git-Spigot-aa47792-6fd677c]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]

Caused by: java.lang.UnsupportedOperationException: Attempted to unregister entity that isn't stacked!
	at uk.antiperson.stackmob.entity.EntityManager.unregisterStackedEntity(EntityManager.java:94) ~[?:?]
	at uk.antiperson.stackmob.entity.EntityManager.unregisterStackedEntities(EntityManager.java:77) ~[?:?]
	at uk.antiperson.stackmob.listeners.ChunkListener.onChunkUnload(ChunkListener.java:23) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor48.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_202]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_202]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[spigot-1.16.4.jar:git-Spigot-aa47792-6fd677c]
	... 19 more
`

**Comment by Nathat23** [comment]
do you do anything to cause it?

**Comment by ScorpioMc** [comment]
No, I didn't edited config file except for mobs that have to be stack. So I don't know what's causing this error

**Comment by Aurelien30000** [comment]
You should update to paper anyways :)

**Comment by ScorpioMc** [comment]
I found another error :

`Caused by: java.lang.NoSuchMethodError: org.bukkit.event.entity.EntityDeathEvent.isCancelled()Z`

I think there's a letter which is causing this error : "Z".

**Comment by Aurelien30000** [comment]
> I found another error :
> 
> `Caused by: java.lang.NoSuchMethodError: org.bukkit.event.entity.EntityDeathEvent.isCancelled()Z`
> 
> I think there's a letter which is causing this error : "Z".
> 
> And I can't go to paper because I'm running Geyser

Hum nope x) Again an issue with Paper, we'll fix it soon!

**Comment by Nathat23** [comment]
> I found another error :
> 
> `Caused by: java.lang.NoSuchMethodError: org.bukkit.event.entity.EntityDeathEvent.isCancelled()Z`
> 
> I think there's a letter which is causing this error : "Z".
> 
> And I can't go to paper because I'm running Geyser

Can you provide the full error?

**Comment by Nathat23** [comment]
> I found another error :
> 
> `Caused by: java.lang.NoSuchMethodError: org.bukkit.event.entity.EntityDeathEvent.isCancelled()Z`
> 
> I think there's a letter which is causing this error : "Z".
> 
> And I can't go to paper because I'm running Geyser

This was fixed in 5.4.2

**Comment by Nathat23** [comment]
Closing since this error cannot occur any more.
