### ISSUE TITLE
Could not pass event EntityDeathEvent to StackMob 

### ISSUE THREAD

**Issue by Boro221** [Nathat23/StackMob-5#183]
Hello. My console is spammed with this error whole time: Could not pass event EntityDeathEvent to StackMob 

I have the latest vesrion of your plugin
My server is running on spigot 1.16.3

[18:49:41] [Server thread/ERROR]: Could not pass event EntityDeathEvent to StackMob v5.4.1
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at org.bukkit.craftbukkit.v1_16_R2.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:764) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.EntityLiving.d(EntityLiving.java:1441) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.EntityLiving.die(EntityLiving.java:1389) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.EntityLiving.damageEntity(EntityLiving.java:1235) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.EntityMonster.damageEntity(SourceFile:73) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.Entity.entityBaseTick(Entity.java:406) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.EntityLiving.entityBaseTick(EntityLiving.java:262) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.EntityInsentient.entityBaseTick(EntityInsentient.java:230) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.Entity.tick(Entity.java:363) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.EntityLiving.tick(EntityLiving.java:2349) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.EntityInsentient.tick(EntityInsentient.java:293) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.WorldServer.entityJoinedWorld(WorldServer.java:659) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.World.a(World.java:718) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.WorldServer.doTick(WorldServer.java:394) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1104) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:349) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1007) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:846) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
Caused by: java.lang.NoSuchMethodError: org.bukkit.event.entity.EntityDeathEvent.setCancelled(Z)V
	at uk.antiperson.stackmob.listeners.DeathListener.onStackDeath(DeathListener.java:55) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor182.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_275]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_275]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[spigot-1.16.3.jar:git-Spigot-2740d5a-890130b]
	... 23 more

**Comment by Nathat23** [comment]
you've configured to skip the death animation but you are not using paper which is required for that function.

**Comment by Boro221** [comment]
i changed it to false and it's still the same

**Comment by Nathat23** [comment]
and you're sure that the file has been saved and that the server has been restarted fully?

**Comment by Aurelien30000** [comment]
You should update to Paper+ anyways :)

**Comment by Nathat23** [comment]
I think this was fixed?
