### ISSUE TITLE
Does not work at Tuinity 1.16.5?

### ISSUE THREAD

**Issue by Misio12320** [Nathat23/StackMob-5#184]
Hi. I have installed this plugin and I get this message when I restart my server:
`[19:08:44 INFO]: [StackMob] Disabling StackMob v5.4.1
[19:08:44 ERROR]: Error occurred while disabling StackMob v5.4.1 (Is it up to date?)
java.lang.UnsupportedOperationException: Attempted to unregister entity that isn't stacked!
        at uk.antiperson.stackmob.entity.EntityManager.unregisterStackedEntity(EntityManager.java:94) ~[?:?]
        at uk.antiperson.stackmob.entity.EntityManager.unregisterStackedEntities(EntityManager.java:77) ~[?:?]
        at uk.antiperson.stackmob.entity.EntityManager.unregisterAllEntities(EntityManager.java:52) ~[?:?]
        at uk.antiperson.stackmob.StackMob.onDisable(StackMob.java:104) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.16.5.jar:git-Tuinity-"502d57b"]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:415) ~[patched_1.16.5.jar:git-Tuinity-"502d57b"]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:516) ~[patched_1.16.5.jar:git-Tuinity-"502d57b"]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:502) ~[patched_1.16.5.jar:git-Tuinity-"502d57b"]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:495) ~[patched_1.16.5.jar:git-Tuinity-"502d57b"]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.disablePlugins(CraftServer.java:434) ~[patched_1.16.5.jar:git-Tuinity-"502d57b"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.stop(MinecraftServer.java:772) ~[patched_1.16.5.jar:git-Tuinity-"502d57b"]
        at net.minecraft.server.v1_16_R3.DedicatedServer.stop(DedicatedServer.java:705) ~[patched_1.16.5.jar:git-Tuinity-"502d57b"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1048) ~[patched_1.16.5.jar:git-Tuinity-"502d57b"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:175) ~[patched_1.16.5.jar:git-Tuinity-"502d57b"]
        at java.lang.Thread.run(Thread.java:834) [?:?]`
Plugins (21): Chunky, ChunkyMap*, Citizens, dynmap*, Essentials, FastAsyncWorldEdit (WorldEdit), HolographicDisplays, LuckPerms, Multiverse-Core, Multiverse-Inventories, PixelPrinter, SAML, ServerRestorer, Shopkeepers, Skent*, Skript, skript-reflect*, StackMob, TuSKe*, Vault, WorldGuard

This server is running Tuinity version git-Tuinity-"502d57b" (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
[19:11:10 INFO]: Checking version, please wait...
[19:11:11 INFO]: Previous version: git-Paper-463 (MC: 1.16.5)
[19:11:11 INFO]: You are running the latest version

**Comment by Nathat23** [comment]
does this occur with paper?

**Comment by Misio12320** [comment]
I did not tested yet. Also my mobs does not stack. I have some cows and they still this same.

**Comment by Nathat23** [comment]
Do they stack if you spawn new mobs with '/sm spawn [entity type] [size]'?

**Comment by Misio12320** [comment]
I did not tested this too but I supposed this plugin will auto stack them

**Comment by Nathat23** [comment]
Well if that command works, then for regular mobs to stack you need to make sure that they were spawned after the plugin was added. You also need to make sure there are 5 of the same type in the same area.

**Comment by Aurelien30000** [comment]
Stackmovb works well on Tuinity, this issue is probably unrelated ;)
