### ISSUE TITLE
[StackMob] Task #714097 for StackMob v5.5.4 generated an exception

### ISSUE THREAD

**Issue by pthoelken** [Nathat23/StackMob-5#217]
A lot of meaningless errors comes up with the latest version of StackMob. I've disable the ProtocolLib in the config and it's also on the latest Version from ProtocolLib. 

https://pastebin.com/raw/eBJWa5vB

![image](https://user-images.githubusercontent.com/12643853/119981266-b6b56f00-bfbd-11eb-9bbf-ffcc8f6a4bd4.png)

![image](https://user-images.githubusercontent.com/12643853/119981307-c5038b00-bfbd-11eb-885c-f0cc000b0a87.png)

**Comment by Nathat23** [comment]
Can you scroll up further in the log to find the original error?

**Comment by pthoelken** [comment]
I think this is one of these: 

```
[18:50:44] [Server thread/ERROR]: [StackMob] Task #1616 for StackMob v5.5.4 generated an exception
[18:50:44] [Server thread/ERROR]: [StackMob] Suspected Plugins: 
[18:50:44] [Server thread/ERROR]: [StackMob] 	StackMob{enabled,ver=5.5.4,path=plugins/StackMob-5.5.4.jar}
[18:50:44] [Server thread/ERROR]: [StackMob] Exception details below: 
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 9
	at java.util.Arrays$ArrayList.set(Arrays.java:4169) ~[?:?]
	at net.minecraft.server.v1_16_R3.NonNullList.set(SourceFile:53) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-115]
	at net.minecraft.server.v1_16_R3.TileEntityLootable.setItem(TileEntityLootable.java:138) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-115]
	at org.bukkit.craftbukkit.v1_16_R3.inventory.CraftInventory.setItem(CraftInventory.java:100) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-115]
	at uk.antiperson.stackmob.listeners.ShearListener.lambda$onShearSheep$0(ShearListener.java:62) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-115]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:469) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-115]
	at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1514) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-115]
	at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:443) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-115]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1423) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-115]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1144) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-115]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-115]
	at java.lang.Thread.run(Thread.java:831) [?:?]
```

It's every time the same major error StackTrace.

**Comment by Nathat23** [comment]
Fixed in afbb00451afbcaa44045f648d0f984d5e3d983fe. You can download the latest build from https://ci.codemc.io/job/Nathat23/job/StackMob-5/ to fix.

**Comment by pthoelken** [comment]
@Nathat23 just for your information. When your put the 5.5.5 version into your plugins folder and start the server this comes up.   

![image](https://user-images.githubusercontent.com/12643853/120077666-d1661180-c0ab-11eb-89b0-9bd074a918c3.png)

**Comment by Nathat23** [comment]
> @Nathat23 just for your information. When your put the 5.5.5 version into your plugins folder and start the server this comes up.
> 
> ![image](https://user-images.githubusercontent.com/12643853/120077666-d1661180-c0ab-11eb-89b0-9bd074a918c3.png)

Spigot sometimes takes a while to update.

**Comment by pthoelken** [comment]
Now i become this message: 

![image](https://user-images.githubusercontent.com/12643853/120080779-b77ffb00-c0ba-11eb-9e1b-f91c0194c3d8.png)

**Comment by Nathat23** [comment]
> Now i become this message:
> 
> ![image](https://user-images.githubusercontent.com/12643853/120080779-b77ffb00-c0ba-11eb-9e1b-f91c0194c3d8.png)

If you download from the link above again this should be fixed,

**Comment by pthoelken** [comment]
Thanks a lot. I will do this tomorrow.

**Comment by pthoelken** [comment]
Oh lord. I don't think that i need more words. Lol ... after your latest update. 

![image](https://user-images.githubusercontent.com/12643853/120098277-46c9f480-c135-11eb-80e1-fc1e0bc28c0a.png)
