### ISSUE TITLE
MythicMobs Hook Disables StackMob

### ISSUE THREAD

**Issue by ShermansWorld** [Nathat23/StackMob-5#246]
**StackMob Version: 5.7.4
MythicMobs Version: 5.0.2
Server Jar: Paper 1.18.2
Java Version: 17**

**Note: The configuration files for both StackMobs and MythicMobs are defaults with no changes. I have experimented with slightly different versions of both plugins and always get the following error:**

java.lang.NoClassDefFoundError: io/lumine/xikage/mythicmobs/MythicMobs
        at uk.antiperson.stackmob.hook.hooks.MythicMobsNoStackHook.onEnable(MythicMobsNoStackHook.java:25) ~[StackMob-5.7.4.jar:?]
        at uk.antiperson.stackmob.hook.HookManager.registerHook(HookManager.java:77) ~[StackMob-5.7.4.jar:?]
        at uk.antiperson.stackmob.hook.HookManager.registerHooks(HookManager.java:48) ~[StackMob-5.7.4.jar:?]
        at uk.antiperson.stackmob.StackMob.onEnable(StackMob.java:74) ~[StackMob-5.7.4.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:559) ~[paper-1.18.2.jar:git-Paper-274]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:473) ~[paper-1.18.2.jar:git-Paper-274]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:664) ~[paper-1.18.2.jar:git-Paper-274]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.18.2.jar:git-Paper-274]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:316) ~[paper-1.18.2.jar:git-Paper-274]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1163) ~[paper-1.18.2.jar:git-Paper-274]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-274]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: io.lumine.xikage.mythicmobs.MythicMobs
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]

**Comment by Nathat23** [comment]
fixed in 5213ae233ad6f23a0e63fe4f9d849a53d4b2d5fe and cb5eaa1e38be02eb957627a75bbc6ba134f6569c
