### ISSUE TITLE
⚠️ 1.19.3 Support

### ISSUE THREAD

**Issue by Lebyy** [Nathat23/StackMob-5#266]
Hello there! After updating the server to Purpur 1.19.3, I have been getting the following error:

```sh
[10:22:08] [Server thread/WARN]: [StackMob] Task #40 for StackMob v5.8.4 generated an exception
com.comphenix.protocol.reflect.FieldAccessException: Field index 0 is out of bounds for length 0
	at com.comphenix.protocol.reflect.FieldAccessException.fromFormat(FieldAccessException.java:49) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:289) ~[ProtocolLib.jar:?]
	at uk.antiperson.stackmob.hook.hooks.ProtocolLibHook.removeFakeArmorStand(ProtocolLibHook.java:118) ~[StackMob-5.8.4.jar:?]
	at uk.antiperson.stackmob.packets.ProtocolLibFakeArmorStand.removeFakeArmorStand(ProtocolLibFakeArmorStand.java:50) ~[StackMob-5.8.4.jar:?]
	at uk.antiperson.stackmob.packets.TagHandler.playerOutRange(TagHandler.java:75) ~[StackMob-5.8.4.jar:?]
	at uk.antiperson.stackmob.packets.PlayerWatcher.checkPlayer(PlayerWatcher.java:57) ~[StackMob-5.8.4.jar:?]
	at uk.antiperson.stackmob.tasks.TagCheckTask.run(TagCheckTask.java:20) ~[StackMob-5.8.4.jar:?]
	at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.3.jar:git-Purpur-1870]
	at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.19.3.jar:git-Purpur-1870]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1500) ~[purpur-1.19.3.jar:git-Purpur-1870]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:482) ~[purpur-1.19.3.jar:git-Purpur-1870]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1424) ~[purpur-1.19.3.jar:git-Purpur-1870]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1194) ~[purpur-1.19.3.jar:git-Purpur-1870]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1870]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

Both ProtocolLib (#607) and StackMob-5 (5.8.4) are up to date.

Server version: git-Purpur-1870

**Comment by Nathat23** [comment]
You can download a build from https://ci.codemc.io/job/Nathat23/job/StackMob-5/ that supports 1.19.3 but there may be some issues still to work out.
