### ISSUE TITLE
Stack value larger then configured

### ISSUE THREAD

**Issue by LogGits** [Nathat23/StackMob-5#28]
Error when using a stack size larger then max size (when modifying stack)
```
WARN 00:55:11
[StackMob]: Plugin StackMob v5.0.2 generated an exception whilst handling conversation input
Console 00:55:11
java.lang.IllegalArgumentException: Stack size cannot be more than the configured stack size!
at uk.antiperson.stackmob.entity.StackEntity.setSize(StackEntity.java:35) ~[?:?]
at uk.antiperson.stackmob.entity.StackEntity.setSize(StackEntity.java:23) ~[?:?]
at uk.antiperson.stackmob.utils.StackingTool$ModifyPrompt.acceptValidatedInput(StackingTool.java:120) ~[?:?]
at org.bukkit.conversations.NumericPrompt.acceptValidatedInput(NumericPrompt.java:37) ~[patched_1.15.1.jar:git-Paper-51]
at org.bukkit.conversations.ValidatingPrompt.acceptInput(ValidatingPrompt.java:30) ~[patched_1.15.1.jar:git-Paper-51]
at org.bukkit.conversations.Conversation.acceptInput(Conversation.java:234) ~[patched_1.15.1.jar:git-Paper-51]
at org.bukkit.craftbukkit.v1_15_R1.conversations.ConversationTracker.acceptConversationInput(ConversationTracker.java:59) ~[patched_1.15.1.jar:git-Paper-51]
at org.bukkit.craftbukkit.v1_15_R1.entity.CraftPlayer.acceptConversationInput(CraftPlayer.java:1443) ~[patched_1.15.1.jar:git-Paper-51]
at net.minecraft.server.v1_15_R1.PlayerConnection$2.run(PlayerConnection.java:1639) ~[patched_1.15.1.jar:git-Paper-51]
at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1192) ~[patched_1.15.1.jar:git-Paper-51]
at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.15.1.jar:git-Paper-51]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1106) ~[patched_1.15.1.jar:git-Paper-51]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:933) ~[patched_1.15.1.jar:git-Paper-51]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
```

**Comment by Nathat23** [comment]
Fixed in above.
