### ISSUE TITLE
Exceptions spam

### ISSUE THREAD

**Issue by LogGits** [Nathat23/StackMob-5#283]
purpur 1.20.4 build 2113, running stackmob 5.8.9 (even on dev build 148)
```
WARN23:32:12
[StackMob]: Task #136 for StackMob v5.8.9 generated an exception
Console23:32:12
java.lang.ExceptionInInitializerError: null
at uk.antiperson.stackmob.libs.adventure.text.serializer.gson.GsonComponentSerializerImpl$Instances.lambda$static$0(GsonComponentSerializerImpl.java:53) ~[StackMob-5.8.9.jar:?]
at java.util.Optional.orElseGet(Optional.java:364) ~[?:?]
at uk.antiperson.stackmob.libs.adventure.text.serializer.gson.GsonComponentSerializerImpl$Instances.<clinit>(GsonComponentSerializerImpl.java:53) ~[StackMob-5.8.9.jar:?]
at uk.antiperson.stackmob.libs.adventure.text.serializer.gson.GsonComponentSerializer.gson(GsonComponentSerializer.java:61) ~[StackMob-5.8.9.jar:?]
at uk.antiperson.stackmob.hook.hooks.ProtocolLibHook.spawnFakeArmorStand(ProtocolLibHook.java:80) ~[StackMob-5.8.9.jar:?]
at uk.antiperson.stackmob.packets.ProtocolLibFakeArmorStand.spawnFakeArmorStand(ProtocolLibFakeArmorStand.java:26) ~[StackMob-5.8.9.jar:?]
at uk.antiperson.stackmob.packets.TagHandler.newlyInRange(TagHandler.java:38) ~[StackMob-5.8.9.jar:?]
at uk.antiperson.stackmob.packets.PlayerWatcher.checkPlayer(PlayerWatcher.java:47) ~[StackMob-5.8.9.jar:?]
at uk.antiperson.stackmob.tasks.TagCheckTask.run(TagCheckTask.java:20) ~[StackMob-5.8.9.jar:?]
at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.4.jar:git-Purpur-2113]
at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[purpur-1.20.4.jar:git-Purpur-2113]
at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1666) ~[purpur-1.20.4.jar:git-Purpur-2113]
at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[purpur-1.20.4.jar:git-Purpur-2113]
at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1545) ~[purpur-1.20.4.jar:git-Purpur-2113]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1235) ~[purpur-1.20.4.jar:git-Purpur-2113]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[purpur-1.20.4.jar:git-Purpur-2113]
at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.lang.IllegalStateException: Key adventure:json/emit/rgb has already been used. Option keys must be unique.
at net.kyori.option.OptionImpl.option(OptionImpl.java:49) ~[option-1.0.0.jar:?]
at net.kyori.option.Option.booleanOption(Option.java:52) ~[option-1.0.0.jar:?]
at uk.antiperson.stackmob.libs.adventure.text.serializer.json.JSONOptions.<clinit>(JSONOptions.java:53) ~[StackMob-5.8.9.jar:?]
... 17 more
WARN23:32:13
[StackMob]: Task #136 for StackMob v5.8.9 generated an exception
Console23:32:13
java.lang.NoClassDefFoundError: Could not initialize class uk.antiperson.stackmob.libs.adventure.text.serializer.gson.GsonComponentSerializerImpl$Instances
at uk.antiperson.stackmob.libs.adventure.text.serializer.gson.GsonComponentSerializer.gson(GsonComponentSerializer.java:61) ~[StackMob-5.8.9.jar:?]
at uk.antiperson.stackmob.hook.hooks.ProtocolLibHook.spawnFakeArmorStand(ProtocolLibHook.java:80) ~[StackMob-5.8.9.jar:?]
at uk.antiperson.stackmob.packets.ProtocolLibFakeArmorStand.spawnFakeArmorStand(ProtocolLibFakeArmorStand.java:26) ~[StackMob-5.8.9.jar:?]
at uk.antiperson.stackmob.packets.TagHandler.newlyInRange(TagHandler.java:38) ~[StackMob-5.8.9.jar:?]
at uk.antiperson.stackmob.packets.PlayerWatcher.checkPlayer(PlayerWatcher.java:47) ~[StackMob-5.8.9.jar:?]
at uk.antiperson.stackmob.tasks.TagCheckTask.run(TagCheckTask.java:20) ~[StackMob-5.8.9.jar:?]
at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.4.jar:git-Purpur-2113]
at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[purpur-1.20.4.jar:git-Purpur-2113]
at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1666) ~[purpur-1.20.4.jar:git-Purpur-2113]
at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[purpur-1.20.4.jar:git-Purpur-2113]
at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1545) ~[purpur-1.20.4.jar:git-Purpur-2113]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1235) ~[purpur-1.20.4.jar:git-Purpur-2113]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:326) ~[purpur-1.20.4.jar:git-Purpur-2113]
at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.ExceptionInInitializerError [in thread "Server thread"]
at uk.antiperson.stackmob.libs.adventure.text.serializer.gson.GsonComponentSerializerImpl$Instances.lambda$static$0(GsonComponentSerializerImpl.java:53) ~[StackMob-5.8.9.jar:?]
at java.util.Optional.orElseGet(Optional.java:364) ~[?:?]
at uk.antiperson.stackmob.libs.adventure.text.serializer.gson.GsonComponentSerializerImpl$Instances.<clinit>(GsonComponentSerializerImpl.java:53) ~[StackMob-5.8.9.jar:?]
... 14 more
```

**Comment by Nathat23** [comment]
Can you check again with latest dev build?

**Comment by LogGits** [comment]
seems like it works
