### ISSUE TITLE
1.20.6 - Multiple issues, packets, ProtocolLib.

### ISSUE THREAD

**Issue by andrewkm** [Nathat23/StackMob-5#287]
@Nathat23

Paper 1.20.6 Build 128
Stackmob latest compiled against https://github.com/Nathat23/StackMob-5/commit/246ca65d6466fd995f34843a91349c03b66f7b68
ProtocolLib compiled against: https://github.com/dmulloy2/ProtocolLib/commit/914bc9aa7f64be287041020ba2be804eb76eb292
```
[08:08:24] [Server thread/WARN]: [StackMob] Task #79 for StackMob v5.8.10 generated an exception
java.lang.NullPointerException: Unable to create packet instance for class class net.minecraft.network.protocol.game.ClientboundAddEntityPacket - true - com.comphenix.protocol.wrappers.WrappedStreamCodec[handle=net.minecraft.network.codec.StreamCodec$5@19c8fa8]
	at java.base/java.util.Objects.requireNonNull(Objects.java:246) ~[?:?]
	at ProtocolLib.jar/com.comphenix.protocol.injector.StructureCache.lambda$newPacket$4(StructureCache.java:130) ~[ProtocolLib.jar:?]
	at ProtocolLib.jar/com.comphenix.protocol.injector.StructureCache.newPacket(StructureCache.java:134) ~[ProtocolLib.jar:?]
	at ProtocolLib.jar/com.comphenix.protocol.injector.StructureCache.newPacket(StructureCache.java:144) ~[ProtocolLib.jar:?]
	at ProtocolLib.jar/com.comphenix.protocol.events.PacketContainer.<init>(PacketContainer.java:119) ~[ProtocolLib.jar:?]
	at StackMob-5.8.10.jar/uk.antiperson.stackmob.hook.hooks.ProtocolLibHook.spawnFakeArmorStand(ProtocolLibHook.java:68) ~[StackMob-5.8.10.jar:?]
	at StackMob-5.8.10.jar/uk.antiperson.stackmob.packets.ProtocolLibFakeArmorStand.spawnFakeArmorStand(ProtocolLibFakeArmorStand.java:26) ~[StackMob-5.8.10.jar:?]
	at StackMob-5.8.10.jar/uk.antiperson.stackmob.packets.TagHandler.newlyInRange(TagHandler.java:38) ~[StackMob-5.8.10.jar:?]
	at StackMob-5.8.10.jar/uk.antiperson.stackmob.packets.PlayerWatcher.checkPlayer(PlayerWatcher.java:47) ~[StackMob-5.8.10.jar:?]
	at StackMob-5.8.10.jar/uk.antiperson.stackmob.tasks.TagCheckTask.run(TagCheckTask.java:20) ~[StackMob-5.8.10.jar:?]
	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.6.jar:1.20.6-128-3181470]
	at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[paper-1.20.6.jar:1.20.6-128-3181470]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1699) ~[paper-1.20.6.jar:1.20.6-128-3181470]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:467) ~[paper-1.20.6.jar:1.20.6-128-3181470]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1571) ~[paper-1.20.6.jar:1.20.6-128-3181470]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1231) ~[paper-1.20.6.jar:1.20.6-128-3181470]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-128-3181470]
	at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
```
&
```
[13:07:05] [Server thread/WARN]: [StackMob] Task #80 for StackMob v5.8.10 generated an exception
com.comphenix.protocol.reflect.FieldAccessException: Field index 0 is out of bounds for length 0
	at ProtocolLib.jar/com.comphenix.protocol.reflect.FieldAccessException.fromFormat(FieldAccessException.java:49) ~[ProtocolLib.jar:?]
	at ProtocolLib.jar/com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:315) ~[ProtocolLib.jar:?]
	at StackMob-5.8.10.jar/uk.antiperson.stackmob.hook.hooks.ProtocolLibHook.removeFakeArmorStand(ProtocolLibHook.java:116) ~[StackMob-5.8.10.jar:?]
	at StackMob-5.8.10.jar/uk.antiperson.stackmob.packets.ProtocolLibFakeArmorStand.removeFakeArmorStand(ProtocolLibFakeArmorStand.java:50) ~[StackMob-5.8.10.jar:?]
	at StackMob-5.8.10.jar/uk.antiperson.stackmob.packets.TagHandler.playerOutRange(TagHandler.java:72) ~[StackMob-5.8.10.jar:?]
	at StackMob-5.8.10.jar/uk.antiperson.stackmob.packets.PlayerWatcher.checkPlayer(PlayerWatcher.java:57) ~[StackMob-5.8.10.jar:?]
	at StackMob-5.8.10.jar/uk.antiperson.stackmob.tasks.TagCheckTask.run(TagCheckTask.java:20) ~[StackMob-5.8.10.jar:?]
	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
	at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1699) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:467) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1571) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1231) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
	at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
```
CC: @dmulloy2

EDIT: We're also now getting this, which happens when a mob is stacked, it boots the players in those loaded chunks:
https://pastebin.com/raw/U5u2fzZ2

**Comment by andrewkm** [comment]
We're also now getting:
https://pastebin.com/raw/vbZcxbCc

Using the latest ProtocolLib: https://github.com/dmulloy2/ProtocolLib/commit/8272ecb33d7a0197ca9c96037cf1d95ca3dd603f

**Comment by andrewkm** [comment]
Tried running the 5.9 branch and getting:

```
[02:15:25] [Server thread/INFO]: [StackMob] Enabling StackMob v5.8.10
[02:15:25] [OkHttp https://plugin.tebex.io/.../INFO]: [Tebex] Connected to EcoCityCraft MainSouth - Minecraft: Java Edition server.
[02:15:25] [Server thread/INFO]: [StackMob] StackMob v5.8.10 by antiPerson and contributors.
[02:15:25] [Server thread/INFO]: [StackMob] GitHub: https://github.com/Nathat23/StackMob-5 Discord: https://discord.gg/fz9xzuB
[02:15:25] [Server thread/INFO]: [StackMob] Loading config files...
[02:15:25] [Server thread/INFO]: [StackMob] Registering hooks and trait checks...
[02:15:25] [Server thread/ERROR]: Error occurred while enabling StackMob v5.8.10 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "uk.antiperson.stackmob.config.EntityConfig.isHookEnabled(String)" because the return value of "uk.antiperson.stackmob.config.MainConfig.getConfig()" is null
	at StackMob-5.8.10.jar/uk.antiperson.stackmob.hook.HookManager.registerHook(HookManager.java:70) ~[StackMob-5.8.10.jar:?]
	at StackMob-5.8.10.jar/uk.antiperson.stackmob.hook.HookManager.registerHooks(HookManager.java:46) ~[StackMob-5.8.10.jar:?]
	at StackMob-5.8.10.jar/uk.antiperson.stackmob.StackMob.onEnable(StackMob.java:87) ~[StackMob-5.8.10.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:519) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:604) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:553) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:675) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:323) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1136) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
	at java.base/java.lang.Thread.run(Thread.java:1570) ~[?:?]
[02:15:25] [Server thread/INFO]: [StackMob] Disabling StackMob v5.8.10
```

**Comment by andrewkm** [comment]
All above issues have been fixed.
Tested against https://github.com/Nathat23/StackMob-5/commit/7e2dd33407d0c7b7dde411bd5ff87312b5744325 & https://github.com/dmulloy2/ProtocolLib/commit/389233f599b6d0008e607f8c498bfb152a130424
