### ISSUE TITLE
1.20.4 issues with latest ProtocolLib

### ISSUE THREAD

**Issue by andrewkm** [Nathat23/StackMob-5#288]
@Nathat23 
Paper 1.20.4 Build 497.
Stackmob on https://github.com/Nathat23/StackMob-5/commit/246ca65d6466fd995f34843a91349c03b66f7b68
ProtocolLib on https://github.com/dmulloy2/ProtocolLib/commit/8272ecb33d7a0197ca9c96037cf1d95ca3dd603f

Mobs are still stacking, but the numbers above heads are gone now it seems.
```
[02:03:50] [Server thread/WARN]: [StackMob] Task #84 for StackMob v5.8.10 generated an exception
java.lang.NoClassDefFoundError: Could not initialize class com.comphenix.protocol.wrappers.InMemoryDataWatcher
	at com.comphenix.protocol.wrappers.WrappedDataWatcher.<init>(WrappedDataWatcher.java:85) ~[ProtocolLib.jar:?]
	at uk.antiperson.stackmob.hook.hooks.ProtocolLibHook.spawnFakeArmorStand(ProtocolLibHook.java:77) ~[StackMob-5.8.10.jar:?]
	at uk.antiperson.stackmob.packets.ProtocolLibFakeArmorStand.spawnFakeArmorStand(ProtocolLibFakeArmorStand.java:26) ~[StackMob-5.8.10.jar:?]
	at uk.antiperson.stackmob.packets.TagHandler.newlyInRange(TagHandler.java:38) ~[StackMob-5.8.10.jar:?]
	at uk.antiperson.stackmob.packets.PlayerWatcher.checkPlayer(PlayerWatcher.java:47) ~[StackMob-5.8.10.jar:?]
	at uk.antiperson.stackmob.tasks.TagCheckTask.run(TagCheckTask.java:20) ~[StackMob-5.8.10.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.4.jar:git-Paper-497]
	at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[paper-1.20.4.jar:git-Paper-497]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1646) ~[paper-1.20.4.jar:git-Paper-497]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.20.4.jar:git-Paper-497]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1525) ~[paper-1.20.4.jar:git-Paper-497]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1226) ~[paper-1.20.4.jar:git-Paper-497]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-497]
	at java.lang.Thread.run(Thread.java:1570) ~[?:?]
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.RuntimeException: Failed to find NMS class: network.syncher.SyncedDataHolder [in thread "Server thread"]
	at com.comphenix.protocol.utility.MinecraftReflection.lambda$getMinecraftClass$4(MinecraftReflection.java:1494) ~[ProtocolLib.jar:?]
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
	at com.comphenix.protocol.utility.MinecraftReflection.getMinecraftClass(MinecraftReflection.java:1494) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.wrappers.InMemoryDataWatcher.<clinit>(InMemoryDataWatcher.java:59) ~[ProtocolLib.jar:?]
	... 14 more
```
CC: @dmulloy2

**Comment by andrewkm** [comment]
https://github.com/dmulloy2/ProtocolLib/commit/914bc9aa7f64be287041020ba2be804eb76eb292 has fixed https://github.com/Nathat23/StackMob-5/issues/288.
