### ISSUE TITLE
Could not pass event EntityDeathEvent to MobHunting

### ISSUE THREAD

**Issue by Amblyopia** [Nathat23/StackMob-5#53]
**Describe the bug**
Whenever a mob is killed that would trigger MobHunting an error is produced and MobHunting is not triggered.

**To Reproduce**
Kill a mob that would trigger MobHunting.

**Expected behavior**
StackMob should pass event normally to trigger any MobHunting effects.

**Bukkit/Spigot AND StackMob version:**
PaperMC 1.15.2 built 118, StackMob 5.0.2

**List of plugins in use:**
AnnouncementsEverywhere-4.0.0.jar
BlockQuest-2.0-pre1.5.jar
Citizens-2.0.26-b1829.jar
CitizensCMD-2.4.jar
CoreProtect-2.18.2.jar
CratesPlus-4.5.3-fixed.jar
EssentialsX-2.17.2.1.jar
EssentialsXChat-2.17.2.1.jar
EssentialsXGeoIP-2.17.2.1.jar
EssentialsXProtect-2.17.2.1.jar
EssentialsXSpawn-2.17.2.1.jar
HolographicDisplays-2.4.2-SNAPSHOT-99.jar
InfernalMobs_6.0.jar
LeaderHeads-4.0.5.jar
LuckPerms-Bukkit-5.0.81.jar
mcMMO-2.1.116.jar
mcMMOHorses-4.3.57.jar
MineableSpawners_2.0.8.jar
MobHunting-7.0.0.jar
Modern-LWC-2.1.5.jar
nuvotifier-2.6.0.jar
OpenInv-4.0.8.jar
PlaceholderAPI-2.10.4.jar
PlayerReport-3.2.11.jar
PlayerShopGUIPlus-1.7.1.jar
PluginConstructorAPI.jar
ProtocolLib_4.5.0.jar
Rankup-3.6.1.jar
RewardMining-1.0.jar
RTP-1.2.jar
ShopGUIPlus-1.25.3.jar
SignSpy-2.7.2b7.jar
Spartan-334.jar
StackMob-5.0.2.jar
SuperVanish-6.1.3.jar
TabList-5.1.jar
TempFly-1.9.0.jar
Towny-0.95.2.0.jar
TownyNameUpdater-4.0.jar
Vault-1.7.2.jar
WarpSystem_v4.1.10.jar
WordGamesPlus-1.4.jar
WorldBorder_1.9.10(beta).jar
worldedit-bukkit-7.1.1-SNAPSHOT-dist-4889.jar

**Error text:**
[12:52:08] [Server thread/ERROR]: Could not pass event EntityDeathEvent to MobHunting v7.0.0
java.lang.NoClassDefFoundError: uk/antiperson/stackmob/api/IStackMob
	at one.lindegaard.MobHunting.modifier.StackedMobBonus.doesApply(StackedMobBonus.java:43) ~[?:?]
	at one.lindegaard.MobHunting.MobHuntingManager.onMobDeath(MobHuntingManager.java:1487) ~[?:?]
	at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.15.2.jar:git-Paper-118]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-118]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-118]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:559) ~[patched_1.15.2.jar:git-Paper-118]
	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:754) ~[patched_1.15.2.jar:git-Paper-118]
	at net.minecraft.server.v1_15_R1.EntityLiving.d(EntityLiving.java:1380) ~[patched_1.15.2.jar:git-Paper-118]
	at net.minecraft.server.v1_15_R1.EntityLiving.die(EntityLiving.java:1308) ~[patched_1.15.2.jar:git-Paper-118]
	at net.minecraft.server.v1_15_R1.EntityLiving.damageEntity(EntityLiving.java:1152) ~[patched_1.15.2.jar:git-Paper-118]
	at net.minecraft.server.v1_15_R1.EntityMonster.damageEntity(EntityMonster.java:52) ~[patched_1.15.2.jar:git-Paper-118]
	at net.minecraft.server.v1_15_R1.EntityZombie.damageEntity(EntityZombie.java:318) ~[patched_1.15.2.jar:git-Paper-118]
	at net.minecraft.server.v1_15_R1.EntityArrow.a(EntityArrow.java:378) ~[patched_1.15.2.jar:git-Paper-118]
	at net.minecraft.server.v1_15_R1.EntityArrow.a(EntityArrow.java:291) ~[patched_1.15.2.jar:git-Paper-118]
	at net.minecraft.server.v1_15_R1.EntityArrow.tick(EntityArrow.java:202) ~[patched_1.15.2.jar:git-Paper-118]
	at net.minecraft.server.v1_15_R1.EntityTippedArrow.tick(EntityTippedArrow.java:92) ~[patched_1.15.2.jar:git-Paper-118]
	at net.minecraft.server.v1_15_R1.WorldServer.entityJoinedWorld(WorldServer.java:759) ~[patched_1.15.2.jar:git-Paper-118]
	at net.minecraft.server.v1_15_R1.World.a(World.java:858) ~[patched_1.15.2.jar:git-Paper-118]
	at net.minecraft.server.v1_15_R1.WorldServer.doTick(WorldServer.java:497) ~[patched_1.15.2.jar:git-Paper-118]
	at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1245) ~[patched_1.15.2.jar:git-Paper-118]
	at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-118]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112) ~[patched_1.15.2.jar:git-Paper-118]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934) ~[patched_1.15.2.jar:git-Paper-118]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
Caused by: java.lang.ClassNotFoundException: uk.antiperson.stackmob.api.IStackMob
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_241]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:171) ~[patched_1.15.2.jar:git-Paper-118]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.15.2.jar:git-Paper-118]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_241]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_241]
	... 24 more

**Comment by Nathat23** [comment]
This is an issue with MobHunting, you should make a ticket there.

**Comment by Amblyopia** [comment]
I have switched to another stacking plugin that does not conflict with MobHunting.
