### ISSUE TITLE
PlayerInteractEntityEvent ClassCastException

### ISSUE THREAD

**Issue by LogGits** [Nathat23/StackMob-5#59]
```
Could not pass event PlayerInteractEntityEvent to StackMob v5.0.2
Console 00:42:45
java.lang.ClassCastException: org.bukkit.craftbukkit.v1_15_R1.entity.CraftMinecartRideable cannot be cast to org.bukkit.entity.LivingEntity
at uk.antiperson.stackmob.listeners.TagInteractListener.onTagInteract(TagInteractListener.java:33) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor638.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-122]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-122]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-122]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:559) ~[patched_1.15.2.jar:git-Paper-122]
at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1998) ~[?:git-Paper-122]
at net.minecraft.server.v1_15_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:51) ~[patched_1.15.2.jar:git-Paper-122]
at net.minecraft.server.v1_15_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:6) ~[patched_1.15.2.jar:git-Paper-122]
at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-122]
at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-122]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-122]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-122]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-122]
at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1038) ~[patched_1.15.2.jar:git-Paper-122]
at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1031) ~[patched_1.15.2.jar:git-Paper-122]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-122]
at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1015) ~[patched_1.15.2.jar:git-Paper-122]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:938) ~[patched_1.15.2.jar:git-Paper-122]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
```
paper 1.15.2 build 126
StackMob 5.0.2

**Comment by Aurelien30000** [comment]
A minecart isn't renameable but this issue could be avoided :)

**Comment by Nathat23** [comment]
Fixed in above commit
