### ISSUE TITLE
Console Spam: Task #102 generated an exception

### ISSUE THREAD

**Issue by Nofsy** [Nathat23/StackMob-5#64]
StackMobs spams the console with the following
> [StackMob] Task Nathat23/StackMob-3#102 for StackMob v5.0.2 generated an exception

Wondering if this is caused by MythicMobs?

**Comment by Nathat23** [comment]
Can you provide the full error?

**Comment by Nofsy** [comment]
> Can you provide the full error?

> [17:26:53] [Server thread/WARN]: [StackMob] Task #102 for StackMob v5.0.2 generated an exception
java.lang.NoClassDefFoundError: net/minecraft/server/v1_15_R1/Packet
	at uk.antiperson.stackmob.tasks.TagTask.sendPacket(TagTask.java:52) ~[?:?]
	at uk.antiperson.stackmob.tasks.TagTask.lambda$run$1(TagTask.java:32) ~[?:?]
	at java.util.ArrayList.forEach(Unknown Source) ~[?:1.8.0_241]
	at uk.antiperson.stackmob.tasks.TagTask.run(TagTask.java:32) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1023) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:396) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:971) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:816) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_15_R1.Packet
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:81) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_241]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_241]
	... 11 more
[17:26:54] [Server thread/WARN]: [StackMob] Task #102 for StackMob v5.0.2 generated an exception
java.lang.NoClassDefFoundError: net/minecraft/server/v1_15_R1/Packet
	at uk.antiperson.stackmob.tasks.TagTask.sendPacket(TagTask.java:52) ~[?:?]
	at uk.antiperson.stackmob.tasks.TagTask.lambda$run$1(TagTask.java:32) ~[?:?]
	at java.util.ArrayList.forEach(Unknown Source) ~[?:1.8.0_241]
	at uk.antiperson.stackmob.tasks.TagTask.run(TagTask.java:32) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1023) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:396) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:971) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:816) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_15_R1.Packet
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:81) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_241]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_241]
	... 11 more

**Comment by Nofsy** [comment]
> [00:00:03] [Server thread/WARN]: [StackMob] Task #102 for StackMob v5.0.2 generated an exception
java.lang.NoClassDefFoundError: net/minecraft/server/v1_15_R1/Packet
	at uk.antiperson.stackmob.tasks.TagTask.sendPacket(TagTask.java:52) ~[?:?]
	at uk.antiperson.stackmob.tasks.TagTask.lambda$run$0(TagTask.java:31) ~[?:?]
	at java.util.ArrayList.forEach(Unknown Source) ~[?:1.8.0_241]
	at uk.antiperson.stackmob.tasks.TagTask.run(TagTask.java:31) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1023) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:396) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:971) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:816) [spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_15_R1.Packet
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:81) ~[spigot-1.14.4.jar:git-Spigot-9de398a-9c887d4]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_241]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_241]
	... 11 more

Any ideas?

**Comment by Nathat23** [comment]
Well, you're using the 1.15 version of StackMob on a 1.14 server. You can change the display-name.mode in the config and this issue will be fixed but you won't be able to update further.
