### ISSUE TITLE
StackMob v5.1.1 generated an exception

### ISSUE THREAD

**Issue by clementinise** [Nathat23/StackMob-5#76]
`[22:10:52] [Server thread/WARN]: [StackMob] Task #626 for StackMob v5.1.1 generated an exception
java.lang.NoClassDefFoundError: net/minecraft/server/v1_15_R1/Packet
	at uk.antiperson.stackmob.tasks.TagTask.sendPacket(TagTask.java:55) ~[?:?]
	at uk.antiperson.stackmob.tasks.TagTask.lambda$run$0(TagTask.java:31) ~[?:?]
	at java.util.ArrayList.forEach(ArrayList.java:1257) ~[?:1.8.0_231]
	at uk.antiperson.stackmob.tasks.TagTask.run(TagTask.java:31) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot.jar:git-Spigot-cbd1a1b-009d8af]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:394) [spigot.jar:git-Spigot-cbd1a1b-009d8af]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1022) [spigot.jar:git-Spigot-cbd1a1b-009d8af]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:393) [spigot.jar:git-Spigot-cbd1a1b-009d8af]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:970) [spigot.jar:git-Spigot-cbd1a1b-009d8af]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:815) [spigot.jar:git-Spigot-cbd1a1b-009d8af]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_231]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_15_R1.Packet
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-cbd1a1b-009d8af]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:81) ~[spigot.jar:git-Spigot-cbd1a1b-009d8af]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_231]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_231]
	... 11 more`

I get this error each secondes on the servers and it makes the server lag sometimes 
(Latest update of Spigot 1.14.4)

**Comment by Nathat23** [comment]
StackMob 5 is for 1.15 only. Either use an older version or update your server software.
