### ISSUE TITLE
Could not pass event EntityDeathEvent 

### ISSUE THREAD

**Issue by pedroramosdiehl** [Nathat23/StackMob-5#83]
`[14:46:51 ERROR]: Could not pass event EntityDeathEvent to StackMob v5.1.1                                                                                                                                                                   java.lang.IllegalArgumentException: Health must be between 0 and 20.0, but was 83.03884887695312. (attribute base value: 20.0)                                                                                                                       at org.bukkit.craftbukkit.v1_15_R1.entity.CraftLivingEntity.setHealth(CraftLivingEntity.java:112) ~[patched_1.15.2.jar:git-Paper-245]                                                                                                        at uk.antiperson.stackmob.entity.death.KillStepDamage.onSpawn(KillStepDamage.java:40) ~[?:?]                                                                                                                                                 at uk.antiperson.stackmob.listeners.DeathListener.onStackDeath(DeathListener.java:40) ~[?:?]                                                                                                                                                 at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor170.execute(Unknown Source) ~[?:?]                                                                                                                             at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-245]                                                                                                                                at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-245]                                                                                                                               at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-245]                                                                                                                            at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-245]                                                                                                                         at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:766) ~[patched_1.15.2.jar:git-Paper-245]                                                                                              at net.minecraft.server.v1_15_R1.EntityLiving.d(EntityLiving.java:1380) ~[patched_1.15.2.jar:git-Paper-245]                                                                                                                                  at net.minecraft.server.v1_15_R1.EntityLiving.die(EntityLiving.java:1308) ~[patched_1.15.2.jar:git-Paper-245]                                                                                                                                at net.minecraft.server.v1_15_R1.EntityLiving.damageEntity(EntityLiving.java:1152) ~[patched_1.15.2.jar:git-Paper-245]                                                                                                                       at net.minecraft.server.v1_15_R1.EntityMonster.damageEntity(EntityMonster.java:52) ~[patched_1.15.2.jar:git-Paper-245]                                                                                                                       at net.minecraft.server.v1_15_R1.EntityZombie.damageEntity(EntityZombie.java:318) ~[patched_1.15.2.jar:git-Paper-245]                                                                                                                        at net.minecraft.server.v1_15_R1.EntityArrow.a(EntityArrow.java:378) ~[patched_1.15.2.jar:git-Paper-245]                                                                                                                                     at net.minecraft.server.v1_15_R1.EntityArrow.a(EntityArrow.java:291) ~[patched_1.15.2.jar:git-Paper-245]                                                                                                                                     at net.minecraft.server.v1_15_R1.EntityArrow.tick(EntityArrow.java:202) ~[patched_1.15.2.jar:git-Paper-245]                                                                                                                                  at net.minecraft.server.v1_15_R1.EntityTippedArrow.tick(EntityTippedArrow.java:92) ~[patched_1.15.2.jar:git-Paper-245]                                                                                                                       at net.minecraft.server.v1_15_R1.WorldServer.entityJoinedWorld(WorldServer.java:803) ~[patched_1.15.2.jar:git-Paper-245]                                                                                                                     at net.minecraft.server.v1_15_R1.World.a(World.java:869) ~[patched_1.15.2.jar:git-Paper-245]                                                                                                                                                 at net.minecraft.server.v1_15_R1.WorldServer.doTick(WorldServer.java:528) ~[patched_1.15.2.jar:git-Paper-245]                                                                                                                                at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1303) ~[patched_1.15.2.jar:git-Paper-245]                                                                                                                            at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-245]                                                                                                                             at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1157) ~[patched_1.15.2.jar:git-Paper-245]                                                                                                                            at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:946) ~[patched_1.15.2.jar:git-Paper-245]                                                                                                                           at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]                                                                        `

**Comment by pedroramosdiehl** [comment]
issue reported here https://github.com/Nathat23/StackMob-5/issues/26
