### ISSUE TITLE
Mob drops are not being duplicated

### ISSUE THREAD

**Issue by Ivan8or** [Nathat23/StackMob-5#87]
I have not been able to get stacks of mobs to drop the correct amount of items. 
I've set the drops to enabled:true and use-loot-tables:true, and set the mode to kill all mobs at once.
The worldguard flag is set to allow mob stacking.

However, when I kill a stack of 100 or so mobs, I only get the drops I would expect from a single mob.

I don't have any plugins that (to my knowledge) mess with the loot tables, though I do have one that completely disables mob AIs.

my list of plugins is as follows:
```
AdvancedHelp
AECommunicate
AuctionHouse
BlowableObsidians
BungeeTabListPlus (Bridge)
BuyCraftX
ChestShop
DisableAI
PhantomEconomy
EpicRename
FogusCore
GoldenCrates
GoldenEnchants
Holograms
LuckPerms
MemCheck
MineableSpawners
MultiChat
NuVotifier
OpenInv
PlayerKits
RTP (random teleport)
SaberFactions
ServerSelectorX
SetSpawn
SimpleTPA
StackMob (version 5.1.1)
Sudo
SuperVanish
UltimateAutoRestart
UltimateHomes
Vault
ViaVersion
ViewDistanceTweaks
VotingPlugin
WorldEdit
WorldGuard

```

The error log says something about the blacklist list being null

```
Could not pass event EntityDeathEvent to StackMob v5.1.1
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot-1.15.1.jar:git-Spigot-037559e-5c6b0dc]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.15.1.jar:git-Spigot-037559e-5c6b0dc]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:529) ~[spigot-1.15.1.jar:git-Spigot-037559e-5c6b0dc]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:514) ~[spigot-1.15.1.jar:git-Spigot-037559e-5c6b0dc]
        at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:721) ~[spigot-1.15.1.jar:git-Spigot-037559e-5c6b0dc]
        at net.minecraft.server.v1_15_R1.EntityLiving.d(EntityLiving.java:1326) ~[spigot-1.15.1.jar:git-Spigot-037559e-5c6b0dc]
        at net.minecraft.server.v1_15_R1.EntityLiving.die(EntityLiving.java:1275) ~[spigot-1.15.1.jar:git-Spigot-037559e-5c6b0dc]
        at net.minecraft.server.v1_15_R1.EntityLiving.damageEntity(EntityLiving.java:1122) ~[spigot-1.15.1.jar:git-Spigot-037559e-5c6b0dc]
        at net.minecraft.server.v1_15_R1.EntityMonster.damageEntity(SourceFile:69) ~[spigot-1.15.1.jar:git-Spigot-037559e-5c6b0dc]
        at net.minecraft.server.v1_15_R1.EntityHuman.attack(EntityHuman.java:1085) ~[spigot-1.15.1.jar:git-Spigot-037559e-5c6b0dc]
        at net.minecraft.server.v1_15_R1.EntityPlayer.attack(EntityPlayer.java:1545) ~[spigot-1.15.1.jar:git-Spigot-037559e-5c6b0dc]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1878) ~[spigot-1.15.1.jar:git-Spigot-037559e-5c6b0dc]
        at net.minecraft.server.v1_15_R1.PacketPlayInUseEntity.a(SourceFile:68) ~[spigot-1.15.1.jar:git-Spigot-037559e-5c6b0dc]
        at net.minecraft.server.v1_15_R1.PacketPlayInUseEntity.a(SourceFile:13) ~[spigot-1.15.1.jar:git-Spigot-037559e-5c6b0dc]
        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[spigot-1.15.1.jar:git-Spigot-037559e-5c6b0dc]
        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) [spigot-1.15.1.jar:git-Spigot-037559e-5c6b0dc]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [spigot-1.15.1.jar:git-Spigot-037559e-5c6b0dc]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [spigot-1.15.1.jar:git-Spigot-037559e-5c6b0dc]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [spigot-1.15.1.jar:git-Spigot-037559e-5c6b0dc]
        at net.minecraft.server.v1_15_R1.MinecraftServer.aZ(MinecraftServer.java:917) [spigot-1.15.1.jar:git-Spigot-037559e-5c6b0dc]
        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:910) [spigot-1.15.1.jar:git-Spigot-037559e-5c6b0dc]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [spigot-1.15.1.jar:git-Spigot-037559e-5c6b0dc]
        at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:894) [spigot-1.15.1.jar:git-Spigot-037559e-5c6b0dc]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:827) [spigot-1.15.1.jar:git-Spigot-037559e-5c6b0dc]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.lang.UnsupportedOperationException: death.ALL.reason-blacklist list is null!
        at uk.antiperson.stackmob.config.ConfigList.contains(ConfigList.java:24) ~[?:?]
        at uk.antiperson.stackmob.config.MainConfig.getDeathType(MainConfig.java:179) ~[?:?]
        at uk.antiperson.stackmob.listeners.DeathListener.calculateDeath(DeathListener.java:62) ~[?:?]
        at uk.antiperson.stackmob.listeners.DeathListener.onStackDeath(DeathListener.java:35) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor85.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.15.1.jar:git-Spigot-037559e-5c6b0dc]
        ... 24 more

```
Here's my config:

```
# How entities should die
death:
  # Death options:
  # SINGLE - Only one entity dies.
  # ALL - Every entity dies.
  # STEP - A random amount dies.
  # STEP_DAMAGE - An amount that depends on the damage done dies.
  #
  # The priority 1 is highest and 4 is lowest.
  # If the killed entity is blacklisted, either by type or death reasons, by the highest priority method,
  # then it will attempt to use the next highest priority death method.
  SINGLE:
    priority: 3
    reason-blacklist: []
    reason-blacklist-invert: false
    type-blacklist: []
    type-blacklist-invert: false
  ALL:
    priority: 1
    reason-blaklist: []
    reason-blacklist-invert: false                                                                                                                                                                       
    type-blacklist: []
    type-blacklist-invert: false
  STEP:
    priority: 4
    reason-blacklist: []
    reason-blacklist-invert: false
    type-blacklist: []
    type-blacklist-invert: false
    max-step: 1
    min-step: 1
  STEP_DAMAGE:
    priority: 2
    reason-blacklist: []
    reason-blacklist-invert: false
    type-blacklist: []
    type-blacklist-invert: false

```

**Comment by Aurelien30000** [comment]
Only happens with a stack or 100+ entities ?

**Comment by Ivan8or** [comment]
> Only happens with a stack of 100+ entities ?

no, it appears to happen with any amount of entities

**Comment by Aurelien30000** [comment]
🤔
